### ISSUE TITLE
omment + F （1234）， 等组合键都没效果

### ISSUE THREAD

**Issue by sunnycn2013** [kzaher/RegX#3] opened 2015-01-08 05:06 UTC
你好，为什么插件安装成功了，但是用的时间comment + F （1234）， 等组合键都没效果，没有教程上的效果。

**Comment by kzaher** [comment] 2015-01-09 17:52
I think that the problem is probably that you don't have mapped function keys as function keys, but as "media keys". I think you can either go to System Preferences > Keyboard > check "Use F1, F2, as standard function keys" or Press Command + fn + function keys (I haven't tested that).

You can set your own shortcuts, just change the configuration file.

**Comment by AngleZhou** [comment] 2015-04-08 10:28
I also met this issue, and wow, your solution perfectly solved it! I think this issue can be marked as closed. 
Thanks for the fantastic plugin and this solution!

**Closed as completed** 2015-04-08 11:00 UTC
